version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sharecount  
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile pour le backend
    ports:
      - "8080:8080"
    environment:
      DB_USER: 'postgres'
      DB_HOST: 'db' 
      DB_DATABASE: 'sharecount'
      DB_PASSWORD: 'postgres'
      DB_PORT: '5432'
      SECRET_SESSION: 'thisismysecrctekeyfhrgfgrfrty84fwir767'

    depends_on:
      - db
    restart: always

volumes:
  postgres-data: